/* Copyright Statement:
 *  This firmware are protected under relevant copyright laws, this information contained
 *  herein is confidential and proprietary to Goodix.
 *
 * GOODIX (C) 2014. All rights reserved.
 *
 * WARNING:
 *  The GTP_COMPATIBLE_MODE part of this file was generated by the specialized tools,
 *  Please do not modify it manually!
 * 
 * Generate date & time: 
 *		2014/10/17, 14:06:06
 */


#ifndef _GT9XX_FIRMWARE_H_
#define _GT9XX_FIRMWARE_H_

struct gtp_fw_info {
	u8 pid[8];
	u8 *fwp;
	unsigned long length;
};

#if GTP_HEADER_FW_UPDATE
unsigned char gtp_gt970_FW[] = {
#include "gt970_201e_1103_0906.ihex"
};

struct gtp_fw_info gtp_update_tb[] = {
	{"970", gtp_gt970_FW, sizeof(gtp_gt970_FW)},
};
#endif /* GTP_HEADER_FW_UPDATE */


#if GTP_COMPATIBLE_MODE
unsigned char gtp_default_FW_fl[] = 
{

};
#endif /* GTP_COMPATIBLE_MODE */

#endif
